/**
 * Genre lookup inferred from film knowledge. Keys are exact film titles as they
 * appear in the BOM scrape. Values are the primary audience-category genre —
 * intentionally broad so filters are useful (not one genre per niche sub-type).
 *
 * Genres: Horror | Action | Animation | Comedy | Drama | Sci-Fi | Thriller | Romance | Documentary | Musical
 */

export type Genre =
  | "Horror"
  | "Action"
  | "Adventure"
  | "Animation"
  | "Comedy"
  | "Drama"
  | "Sci-Fi"
  | "Thriller"
  | "Romance"
  | "Documentary"
  | "Musical";

const GENRE_LOOKUP: Record<string, Genre> = {
  // ── Horror ──────────────────────────────────────────────────────────────────
  "Scream": "Horror",
  "Scream VI": "Horror",
  "Halloween Ends": "Horror",
  "Halloween Kills": "Horror",
  "Smile": "Horror",
  "Smile 2": "Horror",
  "M3GAN": "Horror",
  "Knock at the Cabin": "Horror",
  "Evil Dead Rise": "Horror",
  "The Pope's Exorcist": "Horror",
  "Five Nights at Freddy's": "Horror",
  "The Nun II": "Horror",
  "Imaginary": "Horror",
  "Abigail": "Horror",
  "Longlegs": "Horror",
  "Alien: Romulus": "Horror",
  "Speak No Evil": "Horror",
  "The Substance": "Horror",
  "Terrifier 3": "Horror",
  "Afraid": "Horror",
  "Salem's Lot": "Horror",
  "Beetlejuice Beetlejuice": "Horror",
  "Cocaine Bear": "Horror",
  "Orphan: First Kill": "Horror",
  "The Black Phone": "Horror",
  "Barbarian": "Horror",
  "Texas Chainsaw Massacre": "Horror",
  "X": "Horror",
  "Pearl": "Horror",
  "Firestarter": "Horror",
  "Men": "Horror",
  "Watcher": "Horror",
  "Crimes of the Future": "Horror",
  "Talk to Me": "Horror",
  "Insidious: The Red Door": "Horror",
  "Saw X": "Horror",
  "When Evil Lurks": "Horror",
  "Haunted Mansion": "Horror",
  "Renfield": "Horror",
  "Nope": "Horror",
  "Bodies Bodies Bodies": "Horror",
  "Orphan: First Kill2022 Re-release": "Horror",
  "They/Them": "Horror",
  "Halloween Kills2022 Re-release": "Horror",
  "The Cellar": "Horror",
  "Umma": "Horror",
  "Morbius": "Horror",
  "The Quarry": "Horror",
  "Hatching": "Horror",
  "Hellraiser": "Horror",
  "Prey for the Devil": "Horror",
  "Grimcutty": "Horror",
  "The Cursed": "Horror",
  "Don't Worry Darling": "Thriller",
  "The Strangers: Chapter 1": "Horror",
  "Immaculate": "Horror",
  "The First Omen": "Horror",
  "MaXXXine": "Horror",
  "Tarot": "Horror",
  "Late Night with the Devil": "Horror",
  "I Saw the TV Glow": "Horror",
  "The Watchers": "Horror",
  "A Quiet Place: Day One": "Horror",
  "Blink Twice": "Thriller",
  "Trap": "Thriller",
  "Strange Darling": "Thriller",
  "Transformers: Rise of the Beasts": "Action",

  // ── Action / Adventure / Superhero ──────────────────────────────────────────
  "Spider-Man: No Way Home": "Action",
  "The Batman": "Action",
  "Doctor Strange in the Multiverse of Madness": "Action",
  "Thor: Love and Thunder": "Action",
  "Black Adam": "Action",
  "Black Panther: Wakanda Forever": "Action",
  "Ant-Man and the Wasp: Quantumania": "Action",
  "Guardians of the Galaxy Vol. 3": "Action",
  "The Flash": "Action",
  "Blue Beetle": "Action",
  "The Marvels": "Action",
  "Aquaman and the Lost Kingdom": "Action",
  "Deadpool & Wolverine": "Action",
  "Venom: The Last Dance": "Action",
  "Avatar: The Way of Water": "Action",
  "Top Gun: Maverick": "Action",
  "John Wick: Chapter 4": "Action",
  "Fast X": "Action",
  "Mission: Impossible – Dead Reckoning Part One": "Action",
  "Indiana Jones and the Dial of Destiny": "Action",
  "The Woman King": "Action",
  "Uncharted": "Action",
  "Ambulance": "Action",
  "The Gray Man": "Action",
  "Bullet Train": "Action",
  "Beast": "Action",
  "Violent Night": "Action",
  "Creed III": "Action",
  "65": "Action",
  "The Equalizer 3": "Action",
  "Monkey Man": "Action",
  "The Beekeeper": "Action",
  "Civil War": "Action",
  "The Fall Guy": "Action",
  "Kingdom of the Planet of the Apes": "Action",
  "Furiosa: A Mad Max Saga": "Action",
  "Twisters": "Action",
  "Godzilla x Kong: The New Empire": "Action",
  "Rebel Moon – Part One: A Child of Fire": "Action",
  "Rebel Moon – Part Two: The Scargiver": "Action",
  "Ghostbusters: Frozen Empire": "Action",
  "Argylle": "Action",
  "Dungeons & Dragons: Honor Among Thieves": "Action",
  "The Northman": "Action",
  "The Lost City": "Action",
  "Sonic the Hedgehog 2": "Action",
  "Sonic the Hedgehog 3": "Action",
  "Elvis": "Drama",
  "Moon Knight": "Action",
  "Doctor Strange": "Action",
  "Thor: Ragnarok": "Action",
  "Mortal Kombat": "Action",
  "Shang-Chi and the Legend of the Ten Rings": "Action",
  "Eternals": "Action",
  "Free Guy": "Action",
  "Jungle Cruise": "Action",
  "The Suicide Squad": "Action",
  "G.I. Joe: Snake Eyes": "Action",
  "Old": "Thriller",
  "Black Widow": "Action",
  "Godzilla vs. Kong": "Action",
  "Army of the Dead": "Action",
  "Raya and the Last Dragon": "Animation",
  "Wonder Woman 1984": "Action",
  "F9": "Action",
  "Shang-Chi": "Action",
  "Venom: Let There Be Carnage": "Action",
  "No Time to Die": "Action",
  "The Last Duel": "Action",
  "Dune": "Sci-Fi",
  "Dune: Part Two": "Sci-Fi",
  "Equalizer 3": "Action",
  "Night Swim": "Horror",
  "Anyone But You": "Romance",
  "Mean Girls": "Musical",
  "Wonka": "Musical",
  "Taylor Swift: The Eras Tour": "Documentary",
  "Renaissance: A Film by Beyoncé": "Documentary",
  "Oppenheimer": "Drama",
  "Barbie": "Comedy",
  "Poor Things": "Drama",
  "Killers of the Flower Moon": "Drama",
  "Maestro": "Drama",
  "Priscilla": "Drama",
  "Napoleon": "Drama",
  "Past Lives": "Drama",
  "The Zone of Interest": "Drama",
  "Anatomy of a Fall": "Drama",
  "The Holdovers": "Drama",
  "American Fiction": "Comedy",
  "Society of the Snow": "Drama",
  "Bob Marley: One Love": "Drama",
  "Cabrini": "Drama",
  "The Color Purple": "Drama",
  "Origin": "Drama",
  "A Man Called Otto": "Drama",
  "The Fabelmans": "Drama",
  "Tár": "Drama",
  "Women Talking": "Drama",
  "The Whale": "Drama",
  "Living": "Drama",
  "The Banshees of Inisherin": "Drama",
  "Triangle of Sadness": "Drama",
  "Decision to Leave": "Drama",
  "Argentina, 1985": "Drama",
  "Aftersun": "Drama",
  "All Quiet on the Western Front": "Drama",
  "The Son": "Drama",
  "Empire of Light": "Drama",
  "Babylon": "Drama",
  "Devotion": "Drama",
  "A Beautiful Mind": "Drama",
  "White Noise": "Drama",
  "Amsterdam": "Drama",
  "The Inspection": "Drama",
  "Broker": "Drama",
  "All the Beauty and the Bloodshed": "Documentary",
  "All That Breathes": "Documentary",
  "My Imaginary Country": "Documentary",
  "20 Days in Mariupol": "Documentary",
  "Four Daughters": "Documentary",
  "The Automat": "Documentary",
  "Am I Racist?": "Documentary",
  "After Death": "Documentary",
  "2000 Mules": "Documentary",
  "Sound of Freedom": "Thriller",
  "Missing": "Thriller",
  "A Haunting in Venice": "Thriller",
  "Where the Crawdads Sing": "Thriller",
  "The Menu": "Thriller",
  "Glass Onion: A Knives Out Mystery": "Thriller",
  "Knives Out": "Thriller",
  "See How They Run": "Thriller",
  "Ticket to Paradise": "Romance",
  "It Ends with Us": "Romance",
  "Challengers": "Romance",
  "Fly Me to the Moon": "Romance",
  "About Fate": "Romance",
  "Bros": "Romance",
  "Fire Island": "Romance",
  "Senior Year": "Comedy",
  "The Bubble": "Comedy",
  "The Unbearable Weight of Massive Talent": "Comedy",
  "Everything Everywhere All at Once": "Sci-Fi",
  "The Creator": "Sci-Fi",
  "Rebel Moon": "Sci-Fi",

  // ── Animation ────────────────────────────────────────────────────────────────
  "Puss in Boots: The Last Wish": "Animation",
  "The Super Mario Bros. Movie": "Animation",
  "Spider-Man: Across the Spider-Verse": "Animation",
  "Spider-Man: Beyond the Spider-Verse": "Animation",
  "Minions: The Rise of Gru": "Animation",
  "DC League of Super-Pets": "Animation",
  "Strange World": "Animation",
  "Lyle, Lyle, Crocodile": "Animation",
  "The Boy and the Heron": "Animation",
  "Wish": "Animation",
  "Trolls Band Together": "Animation",
  "Migration": "Animation",
  "Inside Out 2": "Animation",
  "Despicable Me 4": "Animation",
  "The Garfield Movie": "Animation",
  "Kung Fu Panda 4": "Animation",
  "IF": "Animation",
  "Wild Robot": "Animation",
  "Harold and the Purple Crayon": "Animation",
  "Transformers One": "Animation",
  "PAW Patrol: The Mighty Movie": "Animation",
  "Teenage Mutant Ninja Turtles: Mutant Mayhem": "Animation",
  "Turning Red": "Animation",
  "Lightyear": "Animation",
  "Encanto": "Animation",
  "Sing 2": "Animation",
  "The Bad Guys": "Animation",
  "Elemental": "Animation",
  "Nimona": "Animation",
  "Leo": "Animation",
  "My Big Fat Greek Wedding 3": "Comedy",
  "Ruby Gillman, Teenage Kraken": "Animation",
  "Ant-Man": "Action",
  "Shrek 2": "Animation",
  "Moana 2": "Animation",
  "Mufasa: The Lion King": "Animation",
  "The Wild Robot": "Animation",
  "Paddington in Peru": "Animation",

  // ── Comedy ───────────────────────────────────────────────────────────────────
  "80 for Brady": "Comedy",
  "Easter Sunday": "Comedy",
  "About My Father": "Comedy",
  "Good Burger 2": "Comedy",
  "Confess, Fletch": "Comedy",
  "Clerks III": "Comedy",
  "The People We Hate at the Wedding": "Comedy",
  "Spoiler Alert": "Comedy",
  "Marriage Story": "Comedy",
  "Puss in Boots": "Animation",
  "Anchorman": "Comedy",
  "Jackass Forever": "Comedy",
  "The Comeback Trail": "Comedy",
  "No Hard Feelings": "Comedy",
  "You People": "Comedy",
  "The Wedding Year": "Comedy",

  // ── Drama ────────────────────────────────────────────────────────────────────
  "King Richard": "Drama",
  "Power of the Dog": "Drama",
  "Being the Ricardos": "Drama",
  "Belfast": "Drama",
  "The Tragedy of Macbeth": "Drama",
  "West Side Story": "Drama",
  "Spencer": "Drama",
  "The Eyes of Tammy Faye": "Drama",
  "Licorice Pizza": "Drama",
  "C'mon C'mon": "Drama",
  "Red Rocket": "Drama",
  "The Worst Person in the World": "Drama",
  "Drive My Car": "Drama",
  "Flee": "Documentary",
  "Summer of Soul": "Documentary",
  "Judas and the Black Messiah": "Drama",
  "Promising Young Woman": "Drama",
  "Minari": "Drama",
  "The Father": "Drama",
  "Sound of Metal": "Drama",
  "Malcolm & Marie": "Drama",
  "Pieces of a Woman": "Drama",
  "The United States vs. Billie Holiday": "Drama",
  "Nomadland": "Drama",
  "Mank": "Drama",
  "My Brilliant Friend": "Drama",
  "Crouching Tiger, Hidden Dragon": "Action",
  "The Last of the Mohicans": "Action",
  "Memories of Murder": "Thriller",
  "The Green Knight": "Drama",
  "Pig": "Drama",
  "The Hand of God": "Drama",
  "Titane": "Horror",
  "A Hero": "Drama",
  "Great Freedom": "Drama",
  "Bergman Island": "Drama",
  "Paris, 13th District": "Drama",
  "Wheel of Fortune and Fantasy": "Drama",
  "The Card Counter": "Drama",
  "The Sparks Brothers": "Documentary",
  "Ailey": "Documentary",
  "The Velvet Underground": "Documentary",
  "A Chiara": "Drama",
  "Memoria": "Drama",
  "On the Count of Three": "Drama",
  "Petite Maman": "Drama",
  "Parallel Mothers": "Drama",
  "Identifying Features": "Drama",
  "Passing": "Drama",
  "Quo Vadis, Aida?": "Drama",
  "Azor": "Thriller",
  "Compartment No. 6": "Drama",
  "Pleasure": "Drama",
  "One Second": "Drama",
  "Landfall": "Documentary",
  "The Novice": "Drama",
  "Hive": "Drama",
  "Lingui": "Drama",
  "Cow": "Documentary",
  "Together Together": "Drama",
  "We're All Going to the World's Fair": "Horror",
  "The Scary of Sixty-First": "Horror",
  "No Sudden Move": "Thriller",
  "Prisoners": "Thriller",
  "Michael Clayton": "Thriller",
  "All the President's Men": "Thriller",
  "Finch": "Drama",
  "The Harder They Fall": "Action",
  "Last Night in Soho": "Thriller",
  "Stillwater": "Drama",
  "Mass": "Drama",
  "Zola": "Drama",
  "The Dig": "Drama",
  "The Little Things": "Thriller",
  "Riders of Justice": "Action",
  "Coming 2 America": "Comedy",
  "Tom & Jerry": "Animation",
  "Chaos Walking": "Sci-Fi",
  "Cherry": "Drama",
  "I Care a Lot": "Thriller",
  "Moxie": "Drama",
  "Barb and Star Go to Vista Del Mar": "Comedy",
  "News of the World": "Drama",
  "Soul": "Animation",
  "WandaVision": "Action",
  "The Mauritanian": "Drama",
  "Land": "Drama",
  "The Bee Gees": "Documentary",
  "Locked Down": "Comedy",
  "One Night in Miami": "Drama",
  "Sylvie's Love": "Romance",
  "A Beautiful Day in the Neighborhood": "Drama",

  // ── Thriller ─────────────────────────────────────────────────────────────────
  "Emily the Criminal": "Thriller",
  "Kimi": "Thriller",
  "I Came By": "Thriller",
  "The Contractors": "Thriller",
  "Plane": "Action",
  "Luther: The Fallen Sun": "Thriller",
  "Air": "Drama",
  "Marlowe": "Thriller",
  "The Covenant": "Action",
  "Guy Ritchie's The Covenant": "Action",
  "Hypnotic": "Thriller",
  "Heart of Stone": "Action",
  "Retribution": "Thriller",
  "The Kill Room": "Thriller",
  "Thanksgiving": "Horror",
  "Land of Bad": "Action",
  "Drive-Away Dolls": "Comedy",
  "A Different Man": "Drama",
  "Back to Black": "Drama",
  "The Ministry of Ungentlemanly Warfare": "Action",
  "Hit Man": "Comedy",
  "Bad Boys: Ride or Die": "Action",
  "The Bikeriders": "Drama",
  "Horizon: An American Saga": "Drama",
  "Reagan": "Drama",
  "Joker: Folie à Deux": "Drama",
  "Saturday Night": "Drama",
  "A Real Pain": "Drama",
  "Conclave": "Drama",
  "Heretic": "Thriller",
  "Interstellar2024 Re-release": "Sci-Fi",
  "Wicked": "Musical",
  "Gladiator II": "Action",
  "Red One": "Action",
  "The Best Christmas Pageant Ever": "Comedy",
  "Kraven the Hunter": "Action",
  "Nosferatu": "Horror",
  "The Fire Inside": "Drama",
  "Den of Thieves 2: Pantera": "Action",
  "Flight Risk": "Action",
  "Wolf Man": "Horror",
  "One of Them Days": "Comedy",
  "Dog Man": "Animation",
  "The Brutalist": "Drama",
  "Captain America: Brave New World": "Action",
  "Companion": "Thriller",
  "Presence": "Horror",
  "Bridget Jones: Mad About the Boy": "Romance",
  "Mickey 17": "Sci-Fi",
  "Novocaine": "Action",
  "The Accountant 2": "Action",
  "A Working Man": "Action",
  "Black Bag": "Thriller",
  "A Complete Unknown": "Drama",

  // ── Sci-Fi ───────────────────────────────────────────────────────────────────
  "The Adam Project": "Sci-Fi",
  "Infinite": "Sci-Fi",
  "Moonfall": "Sci-Fi",
  "After Yang": "Sci-Fi",
  "Bigbug": "Sci-Fi",
  "The Matrix Resurrections": "Sci-Fi",
  "Don't Look Up": "Sci-Fi",
  "Stowaway": "Sci-Fi",
  "Those Who Wish Me Dead": "Action",
  "The Tomorrow War": "Sci-Fi",
  "The Mitchells vs. the Machines": "Animation",
  "Oxygen": "Sci-Fi",

  // ── Romance ──────────────────────────────────────────────────────────────────
  "Happiest Season": "Romance",
  "The Kissing Booth 3": "Romance",
  "He's All That": "Romance",
  "Love Hard": "Romance",
  "Single All the Way": "Romance",
  "A Castle for Christmas": "Romance",
  "Holidate": "Romance",
  "The Lovebirds": "Romance",
  "The High Note": "Romance",
  "To All the Boys: Always and Forever": "Romance",
  "Yes Day": "Comedy",
  "The Map of Tiny Perfect Things": "Romance",
  "Bloom": "Romance",

  // ── Documentary ──────────────────────────────────────────────────────────────
  "Sparks Brothers": "Documentary",
  "Turn Every Page: The Adventures of Robert Caro and Robert Gottlieb": "Documentary",
  "Fire of Love": "Documentary",
  "Moonage Daydream": "Documentary",
  "I Am Vanessa Guillen": "Documentary",
  "Sr.": "Documentary",
  "George Carlin's American Dream": "Documentary",
  "The Territory": "Documentary",
  "Good Night Oppy": "Documentary",
  "Descendant": "Documentary",
  "Listen to Me Marlon": "Documentary",
  "Exposure": "Documentary",
  "The Janes": "Documentary",
  "Navalny": "Documentary",
  "Last Flight Home": "Documentary",
  "Return to Space": "Documentary",
  "The Andy Warhol Diaries": "Documentary",
  "Bad Vegan: Fame. Fraud. Fugitives.": "Documentary",
  "Pray Away": "Documentary",
  "Roadrunner: A Film About Anthony Bourdain": "Documentary",
  "Val": "Documentary",
  "The Rescue": "Documentary",
  "Icarus": "Documentary",
  "Erik the Viking": "Documentary",
  "In the Same Breath": "Documentary",
  "Aziz Ansari: Nightclub Comedian": "Documentary",
  "How to Change Your Mind": "Documentary",
  "Jeen-Yuhs: A Kanye Trilogy": "Documentary",
  "Echoes of the Past": "Documentary",

  // ── Musical ──────────────────────────────────────────────────────────────────
  "Dear Evan Hansen": "Musical",
  "Tick, Tick... Boom!": "Musical",
  "In the Heights": "Musical",
  "Annette": "Musical",
  "Greatest Showman2022 Re-release": "Musical",
  "Greatest Showman": "Musical",
  "Les Misérables": "Musical",
  "La La Land": "Musical",
  "Bohemian Rhapsody": "Musical",
  "Rocketman": "Musical",
  "Yesterday": "Musical",
  "Cats": "Musical",
  "Judy": "Musical",
  "Mamma Mia! Here We Go Again": "Musical",
  "The Greatest Showman": "Musical",
  "Beauty and the Beast": "Musical",
};

export function inferGenre(filmTitle: string): Genre | null {
  if (!filmTitle) return null;

  // Direct lookup first
  const direct = GENRE_LOOKUP[filmTitle];
  if (direct) return direct;

  // Strip common suffixes like "2022 Re-release", "4K Restoration", etc.
  const cleaned = filmTitle.replace(/\d{4}\s+Re-release$/i, "")
    .replace(/\d{4}\s+Re-release\s*-.*$/i, "")
    .replace(/\s*(4K|4k)\s+Restoration.*$/i, "")
    .replace(/\s*\d+(th|st|nd|rd)\s+Anniversary.*$/i, "")
    .trim();

  if (cleaned !== filmTitle) {
    const cleanedLookup = GENRE_LOOKUP[cleaned];
    if (cleanedLookup) return cleanedLookup;
  }

  return null;
}

export const ALL_GENRES: Genre[] = [
  "Horror",
  "Action",
  "Adventure",
  "Animation",
  "Comedy",
  "Drama",
  "Sci-Fi",
  "Thriller",
  "Romance",
  "Documentary",
  "Musical",
];

// Maps The Numbers genre strings to our Genre type.
// "Thriller/Suspense" and "Thriller" both → "Thriller", etc.
const NUMBERS_GENRE_MAP: Partial<Record<string, Genre>> = {
  "Action": "Action",
  "Adventure": "Adventure",
  "Animation": "Animation",
  "Black Comedy": "Comedy",
  "Comedy": "Comedy",
  "Concert/Performance": "Documentary",
  "Documentary": "Documentary",
  "Drama": "Drama",
  "Horror": "Horror",
  "Musical": "Musical",
  "Reality": "Documentary",
  "Romance": "Romance",
  "Romantic Comedy": "Romance",
  "Sci-Fi": "Sci-Fi",
  "Thriller": "Thriller",
  "Thriller/Suspense": "Thriller",
  "Western": "Action",
};

export function normalizeNumbersGenre(genre: string | null | undefined): Genre | null {
  if (!genre) return null;
  return NUMBERS_GENRE_MAP[genre] ?? null;
}
